

/*****************  CORONA VIRUS ANALYSIS *****************/


-- Q1. Write a code to check NULL values

SELECT COUNTRY,Date,CONFIRMED,DEATHS,RECOVERED
FROM CORONA_VIRUS_INFO WHERE COUNTRY IS NULL
AND Date IS NULL
AND CONFIRMED IS NULL
AND DEATHS IS NULL
AND RECOVERED IS NULL;


--Q2. If NULL values are present, update them with zeros for all columns.

-- There is no null values.


-- Q3. check total number of rows.

select count(*) from corona_virus_info;


-- Q4. Check what is start_date and end_date

SELECT MIN(Date) AS START_DATE,MAX(date) AS END_DATE
FROM CORONA_VIRUS_INFO;


-- Q5. Number of month present in dataset

SELECT COUNT(DISTINCT(EXTRACT(MONTH FROM DATE))) AS MONTHS
FROM CORONA_VIRUS_INFO
ORDER BY MONTHS;


-- Q6. Find monthly average for confirmed, deaths, recovered.

WITH CTE AS
	(
		SELECT COUNTRY,DATE,CONFIRMED,DEATHS,RECOVERED,
		EXTRACT(YEAR FROM DATE) AS YEARS,
		TO_CHAR(DATE_TRUNC('month',DATE),'Month') AS CHAR_MONTHS
		FROM CORONA_VIRUS_INFO
	)
SELECT DISTINCT COUNTRY,CHAR_MONTHS,YEARS,
	AVG(CONFIRMED) OVER (PARTITION BY CHAR_MONTHS,YEARS) AS AVG_CONFIRMED,
	AVG(DEATHS) OVER (PARTITION BY CHAR_MONTHS,YEARS) AS AVG_DEATHS,
	AVG(RECOVERED) OVER (PARTITION BY CHAR_MONTHS,YEARS) AS AVG_RECOVERED
FROM CTE
ORDER BY COUNTRY,CHAR_MONTHS;


-- Q7. Find most frequent value for confirmed, deaths, recovered each month 

-- at last


-- Q8. Find minimum values for confirmed, deaths, recovered per year

WITH CTE AS
	(
		SELECT COUNTRY,DATE,CONFIRMED,DEATHS,RECOVERED,
		EXTRACT(YEAR FROM DATE) AS YEARS
		FROM CORONA_VIRUS_INFO
	)
SELECT DISTINCT COUNTRY,YEARS,MIN(CONFIRMED) AS MIN_CONFIRMED,
MIN(DEATHS) AS MIN_DEATHS,MIN(RECOVERED) AS MIN_RECOVERED
FROM CTE GROUP BY COUNTRY,YEARS
ORDER BY COUNTRY,YEARS;


-- Q9. Find maximum values of confirmed, deaths, recovered per year

WITH CTE AS
	(
		SELECT COUNTRY,DATE,CONFIRMED,DEATHS,RECOVERED,
		EXTRACT(YEAR FROM DATE) AS YEARS
		FROM CORONA_VIRUS_INFO
	)
SELECT DISTINCT COUNTRY,YEARS,MAX(CONFIRMED) AS MAX_CONFIRMED,
MAX(DEATHS) AS MAX_DEATHS,MAX(RECOVERED) AS MAX_RECOVERED
FROM CTE GROUP BY COUNTRY,YEARS
ORDER BY COUNTRY,YEARS;


-- Q10. The total number of case of confirmed, deaths, recovered each month

WITH CTE AS
	(
		SELECT COUNTRY,DATE,CONFIRMED,DEATHS,RECOVERED,
		TO_CHAR(DATE_TRUNC('month',Date),'Month') as MONTHS,
		EXTRACT(YEAR FROM DATE) AS YEARS
		FROM CORONA_VIRUS_INFO
	)
SELECT COUNTRY,MONTHS,YEARS,
	SUM(CONFIRMED) AS TOTAL_CONFIRMED,
	SUM(DEATHS) AS TOTAL_DEATHS,
	SUM(RECOVERED) AS TOTAL_RECOVERED
FROM CTE
GROUP BY COUNTRY,MONTHS,YEARS
ORDER BY COUNTRY,MONTHS,YEARS;


/* Q11. Check how corona virus spread out with respect to confirmed case
   (Eg.: total confirmed cases, their average, variance & STDEV ) 
*/

SELECT COUNTRY,ROUND(SUM(CONFIRMED),2) AS TOTAL_CONFIRMED,
	   ROUND(AVG(CONFIRMED),2) AS AVG_CONFIRMED,
	   ROUND(VAR_POP(CONFIRMED),2) AS CONFIRMED_VARIANCE,
	   ROUND(STDDEV_POP(CONFIRMED),2) AS CONFIRMED_STANDARD_DEVATION
FROM CORONA_VIRUS_INFO
GROUP BY COUNTRY
ORDER BY COUNTRY;


/* Q12. Check how corona virus spread out with respect to death case per month
   (Eg.: total confirmed cases, their average, variance & STDEV )
*/

SELECT COUNTRY,TO_CHAR(DATE_TRUNC('month',date),'Month') AS MONTHS,
	ROUND(SUM(DEATHS),2) AS TOTAL_DEATHS,
	ROUND(AVG(DEATHS),2) AS AVG_DEATHS,
	ROUND(VAR_POP(DEATHS),2) AS DEATHS_VARIANCE,
	ROUND(STDDEV_POP(DEATHS),2) AS DEATHS_STANDARD_DEVATION
FROM CORONA_VIRUS_INFO
GROUP BY COUNTRY,MONTHS
ORDER BY COUNTRY,MONTHS;


/* Q13. Check how corona virus spread out with respect to recovered case
   (Eg.: total confirmed cases, their average, variance & STDEV )
*/

SELECT COUNTRY,ROUND(SUM(RECOVERED),2) AS TOTAL_RECOVERED,
	   ROUND(AVG(RECOVERED),2) AS AVG_RECOVERED,
	   ROUND(VAR_POP(RECOVERED),2) AS RECOVERED_VARIANCE,
	   ROUND(STDDEV_POP(RECOVERED),2) AS RECOVERED_STANDARD_DEVATION
FROM CORONA_VIRUS_INFO
GROUP BY COUNTRY
ORDER BY COUNTRY;


-- Q14. Find Country having highest number of the Confirmed case

SELECT X.COUNTRY,X.MONTHS,X.YEARS,
	   MAX(X.CONFIRMED) AS HIGHEST_CONFIRMED_CASES
FROM
	(
		SELECT COUNTRY,CONFIRMED,
		TO_CHAR(DATE_TRUNC('month',date),'Month') AS MONTHS,
		EXTRACT(YEAR FROM date) AS YEARS
		FROM CORONA_VIRUS_INFO
	) X
GROUP BY COUNTRY,MONTHS,YEARS
ORDER BY HIGHEST_CONFIRMED_CASES DESC


-- Q15. Find Country having lowest number of the death case

SELECT X.COUNTRY,X.MONTHS,X.YEARS,
	   MIN(X.DEATHS) AS LOWEST_DEATH_CASES
FROM
	(
		SELECT COUNTRY,DEATHS,
		TO_CHAR(DATE_TRUNC('month',date),'Month') AS MONTHS,
		EXTRACT(YEAR FROM date) AS YEARS
		FROM CORONA_VIRUS_INFO
	) X
GROUP BY COUNTRY,MONTHS,YEARS
ORDER BY LOWEST_DEATH_CASES;


-- Q16. Find top 5 countries having highest recovered case

SELECT X.COUNTRY,X.MONTHS,X.YEARS,
	   MIN(X.RECOVERED) AS RECOVERED_CASES
FROM
	(
		SELECT COUNTRY,RECOVERED,
		TO_CHAR(DATE_TRUNC('month',date),'Month') AS MONTHS,
		EXTRACT(YEAR FROM date) AS YEARS
		FROM CORONA_VIRUS_INFO
	) X
GROUP BY COUNTRY,MONTHS,YEARS
ORDER BY RECOVERED_CASES DESC
LIMIT 5;